import Section2 from "@/Component/Section2";


export default function Home() {
  return (
    <>
        <Section2/>
    </>
  );
}


export const metadata = {
  title: "Video - A Story Teller",
  description: "Generated by create next app",
};