import Section1 from "@/Component/Section1";

export default function Home() {
  return (
    <>
        <Section1/>
    </>
  );
}


export const metadata = {
  title: "About - A Story Teller",
  description: "Generated by create next app",
};