import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "A Story Teller - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <img src="https://yt3.googleusercontent.com/YNhVdBnQ1qd1tgPflKFjMPg6CvuXThwqchjoy7n1inwwchZzt__tbYHjfspoffo-_soUgiqt=w1138-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj"
        height={100}
        width={100}
        className="h-full w-full "
        />
        {children}
      </body>
    </html>
  );
}
